#!/usr/bin/env python3

import os, sys, helpers, nltk
from analyzer import Analyzer
from termcolor import colored

def main():

	if len(sys.argv) != 2:
		sys.exit("Usage : ./tweets @(user)")

	positives = os.path.join(sys.path[0], "positive-words.txt")
	negatives = os.path.join(sys.path[0], "negative-words.txt")

	analyzer = Analyzer(positives, negatives)

	tweets = helpers.get_user_timeline(sys.argv[1], 10)

	if tweets == None:
		sys.exit("Invalid User")

	# tokenizer = nltk.tokenize.TweetTokenizer()
	# tokens = tokenizer.tokenize(tweets)
	for i in tweets:
		num = analyzer.analyze(i)
		if num > 0.0:
			print(" " + colored(num, "green"), end='')
			print(' ' + colored(i, "green"))
		elif num < 0.0:
			print(colored(num, "red"), end='')
			print(' ' + colored(i, "red"))
		else:
			print(" " + colored(num, "yellow"), end='')
			print(' ' + colored(i, "yellow"))
	# print(tweets)




if __name__ == "__main__":
	main()